### ISSUE TITLE
gmonitor: command not found

### ISSUE THREAD

**Issue by hjsg1010** [mountassir/gmonitor#17]
![스크린샷, 2019-05-22 13-18-10](https://user-images.githubusercontent.com/17421673/58147179-3fdd9100-7c94-11e9-8893-8fe1946bda2e.png)

As can be seen in upon figure, I can not run gmonitor ; gmonitor : command not found
I can run gpu monitoring tools such as nvidia-smi, glance or gpustat. 
However, I can not run your program.. I really want to use it. Please help me.

**Comment by mountassir** [comment]
Actually, just realized from the screen shot that you cloned gmonitor inside /usr/local/bin/. This means that when CMake tries to install gmonitor inside /usr/local/bin/, it fails because you already have a directory  in there with the same name.

Try this
Go to your home directory
``` bash 
$ cd ~
```
Remove old gmonitor source code
``` bash
$ sudo rm -r /usr/local/bin/gmonitor
```
Clone a new copy of gmonitor source code (**while you are in your home directory**) 
``` bash
$ git clone https://github.com/mountassir/gmonitor.git
```
Then build and install
``` bash
$ cd gmonitor
$ mkdir build
$ cd build
$ cmake ..
$ make
$ sudo make install
```

**Comment by hjsg1010** [comment]
@mountassir 
Thx, I solved the previous problem.
However, I get other issue.
![스크린샷, 2019-05-24 10-28-37](https://user-images.githubusercontent.com/17421673/58296487-cf0eb400-7e0e-11e9-96b2-c035514be56a.png)

Thx for reply.

**Comment by hjsg1010** [comment]
oh, I think this issues occur because I use this in ssh server... 
does it solved?

sorry for my poor english skills

**Comment by mountassir** [comment]
You need to add -s to your gmonitor run command if you are connecting to your server through SSH.

```` bash
$ gmonitor -s -d 1
````

**Comment by hjsg1010** [comment]
@mountassir Oh..Thank you very much.. my stupid.. I should read README.md more ..

**Comment by mountassir** [comment]
No worries.
